[package]
name = "async_calc_client"
version = "0.1.0"
authors = ["Hasan Ibraheem <hasantiny@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
futures-util = "0.3"
futures-io = "0.3"
tokio = "0.2.0-alpha.6"

[dependencies.async_calc_utils]
path = "../utils"
version = "0.1.0"
